version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    volumes: 
      - ".:/app"
    # ports: 
    #   - "8082:8080"
    networks:
      - network
    stdin_open: true
    command: ['/bin/bash']
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./nginx_templates:/etc/nginx/templates"
    ports:
      - 4200:80
    depends_on:
      - api
    networks:
      - network
networks:
  network:
    
    